task_name: bin_packing
exp_name: 
is_save: True
max_predicates: 2
data_dir: 
json_dir: 
result_dir: 
input_image: 
api_json: 
example_prompt_json: 
robot_json: robot.json
task_json: task_instruction.json
seed: 42
